# .git-metadata.yml - Repository-wide metadata
repository:
  name: architecture-repository
  type: TOGAF Architecture Repository
  version: 1.0.0
  owner: Enterprise Architecture Team
  created: 2025-01-15
  classification: Internal
  
governance:
  review_board: architecture-review-board@company.com
  review_cycle: monthly
  compliance_framework: TOGAF 10
  
integrations:
  confluence_space: EARCH
  jira_project: EARCH
  slack_channel: "#architecture"
